### ISSUE TITLE
最新RsNPC无法使用

### ISSUE THREAD

**Issue by gougocoffee** [lt-name/RsNpcVariable#1]
-最新RsNPC无法使用

**Comment by gougocoffee** [comment]
![image](https://user-images.githubusercontent.com/49330438/176459222-1b89b26a-f13b-46e4-a6c6-faa559784f75.png)

**Comment by lt-name** [comment]
已修复

**Comment by gougocoffee** [comment]
安装后控制台报错，部分NPC不显示。
![image](https://user-images.githubusercontent.com/49330438/176672948-fde8de79-a565-4332-b4d7-cc84ae4d61c4.png)
